-- CAST Y CONVERT
SELECT 
9.5 AS ORIGINAL, 
CAST(9.5 AS INT) AS INT,
CAST(9.5 AS DECIMAL(6,4)) AS DECIMAL;

DECLARE @Anio INT= 2018;
PRINT 'Año:' + @Anio
-- Error de conversión al convertir el valor varchar 'Año:' al tipo de datos int.
GO
DECLARE @Anio INT= 2018;
PRINT 'Año:' + CAST(@Anio AS VARCHAR)

SELECT 
CONVERT(VARCHAR, GETDATE(), 101),
CONVERT(VARCHAR, GETDATE(), 103), 
CONVERT(VARCHAR, GETDATE(), 105), 
CONVERT(VARCHAR, GETDATE(), 111), 
CONVERT(VARCHAR, GETDATE(), 112)


